version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: leansight-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-models:/models
    environment:
      - OLLAMA_MODELS=/models
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - leansight-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  ollama-init:
    image: ollama/ollama:latest
    container_name: leansight-ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./scripts/init-models.sh:/init-models.sh
    command: /bin/bash /init-models.sh
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - leansight-network
    restart: "no"

  # Optional: Web UI for Ollama management
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: leansight-ollama-webui
    ports:
      - "3001:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-here
    volumes:
      - ollama_webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - leansight-network
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
  ollama_webui_data:
    driver: local

networks:
  leansight-network:
    driver: bridge 